<?php /** @var \Magento\Backend\Block\Template\Context $block */ ?>
<form method="post" enctype="multipart/form-data">
    <label for="image_title">Title</label>
    <input type="text" id="image_title" name="title" value="<?= $block->escapeHtml($block->getTitle()) ?>" />
    
    <label for="image_file">Image</label>
    <input type="file" id="image_file" name="image" />
    
    <button type="submit">Save</button>
</form>
