<div class="counter_components" style="margin-bottom: 74px;">
  <img class="rotate_img" src="<?php echo $block->getViewFileUrl('images/counter-vector.png'); ?>" alt="Flatiron Building" />
  <div class="text" style="maragin-left:1000px;">Free <span style="color:red">Shipping</span><br> On all Order</div>
  <img src="<?php echo $block->getViewFileUrl('images/arrow.png'); ?>"/>
  <h6 style="font-size: 59px;">12K</h6>
  <div class="counter-text" style="font-size: x-large;">Furniture Product For <br> Home</div>
  <h6 style="font-size: 59px;">120k</h6>
  <div class="counter-text" style="font-size: x-large;">Our Satiesfiyed Clients </div>
</div>

