<?php /** @var \Magetop\Helloworld\Block\Posts $block */ ?>
<?php $posts = $block->getPostItems(); ?>
<div class="post-content">
    <table style="width:100%">
        <tr>
            <th><?php echo __('Title') ?></th>
            <th><?php echo __('Description') ?></th>
            <th><?php echo __('Image') ?></th>
        </tr>
        <?php if (count($posts)) : ?>
            <?php foreach ($posts as $post) : ?>
                <tr>
                    <td><?php echo $post->getTitle() ?></td>
                    <td><?php echo $post->getDescription() ?></td>
                    <td>
                        <?php $image = $post->getImage(); ?>
                        <?php if ($image): ?>
                            <img src="<?php echo $block->getViewFileUrl('media/helloworld/images/' . $image); ?>" width="100" height="100"/>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
</div>
